name: Update Difficulty Directory
on: [push, pull_request]
jobs:

  build:
    name: "Update Difficulty Directory"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh
        env:
          SSH_KEY: ${{ secrets.KIVINSAE_PRIV_RSAKEY }}

      - name: Clone and cd into the repo
        run: |-
          git clone git@github.com:KKtheGhost/Kivinsae-LeetCode-C.git
          cd Kivinsae-LeetCode-C
          ./Link_Gen.sh

      - name: Commit and push
        run: |-
          git config --global user.email "kivinsae@gmail.com" && git config --global user.name "KKtheGhost"
          git diff
          git add .
          git config pull.rebase false
          git pull && git push